version: '2'

services:
  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=varo
      - POSTGRES_PASSWORD=varo
      - POSTGRES_DB=backend-test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
  app:
    image: 'app'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend-test
      - SPRING_DATASOURCE_USERNAME=varo
      - SPRING_DATASOURCE_PASSWORD=varo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db